version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/synaptix/postgres:/var/lib/synaptix/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cretn0
      - POSTGRES_USER=synaptix_admin
      - POSTGRES_DB=synaptix_db

  backend:
    build: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - postgres

#  nginx:
#    build: ./nginx/
#    ports:
#      -  80:80
  
#  frontend:
#    build: ./frontend/
#    ports:
#     - 3000:3000
#    depends_on:
#     - backend

volumes:
  postgres:
